index-url = "https://mirrors.aliyun.com/pypi/simple/"
extra-index-url = [
    "https://mirrors.aliyun.com/pypi/simple/",
    "https://pypi.tuna.tsinghua.edu.cn/simple"
]

concurrent-downloads = 1
concurrent-builds = 1
concurrent-installs = 1
